### ISSUE TITLE
Should throw NotFoundException instead of just Exception when route doesn't exist

### ISSUE THREAD

**Issue by Soviut** [ecoal95/php-router#5]
Currently, if a route doesn't exist, a general Exception is thrown. This makes it difficult to handle route-related exceptions while letting other more serious exceptions pass through.

It would be nice if some sort of "NotFoundException" was thrown instead. It would seem that you'll need to make a custom exception to do this since PHP doesn't have a built in one like this.

http://php.net/manual/en/spl.exceptions.php

**Comment by emilio** [comment]
Thanks for the suggestion, I changed it to `RouteNotFoundException`, since I found it more appropiate.

Also added CI and a few tests, if you have any other suggestion, they are welcome :P
