### ISSUE TITLE
Redirect shortcut

### ISSUE THREAD

**Issue by Soviut** [ecoal95/php-router#6]
It'd be nice if there was a redirect shortcut to turn this:

``` php
$router->all('/connect', function() {
    header("Location: /connect/search");
    exit;
});
```

into:

``` php
$router->redirect('/connect', '/connect/search');
```

AngularJS has a similar mechanism in their router.

**Comment by emilio** [comment]
https://github.com/ecoal95/php-router/commit/e1c205806572b412a0c9199de9b7299c214525af
